// GENERATED by figma2flutter — shared asset catalog. Do not edit by hand.
// Project 'fashion_app': same-bytes assets are deduped to one file + one const.
class FashionAppAssets {
  FashionAppAssets._();
  static const String a5 = 'assets/images/9e9c80d3c64a.svg';
  static const String close = 'assets/images/d6d642e75bd5.svg';
  static const String down = 'assets/images/93315dc39afd.svg';
  static const String ellipse66Stroke = 'assets/images/81f58e39b384.svg';
  static const String exportAsset = 'assets/images/94d785a26db0.svg';
  static const String filter = 'assets/images/a406bb860ff2.svg';
  static const String forward = 'assets/images/15d43f11d16d.svg';
  static const String forward2 = 'assets/images/3113da754f35.svg';
  static const String forward3 = 'assets/images/5059f8e3247c.svg';
  static const String gallery = 'assets/images/63b925f38c71.svg';
  static const String header2 = 'assets/images/d7c5c9b31586.svg';
  static const String header3 = 'assets/images/af6cc402d5ae.svg';
  static const String heart4 = 'assets/images/420b9b54d966.svg';
  static const String heart5 = 'assets/images/e5a0b98fa6ab.svg';
  static const String image16 = 'assets/images/9a3b1487c944.png';
  static const String image17 = 'assets/images/87dcbd2a1917.png';
  static const String image18 = 'assets/images/3efc64f26ee9.png';
  static const String img = 'assets/images/96f5e53cc367.png';
  static const String instagram3 = 'assets/images/bb8040996685.svg';
  static const String plus = 'assets/images/25f2bcc9f7ea.svg';
  static const String refresh = 'assets/images/8bf3713b8594.svg';
  static const String tag = 'assets/images/02e24c5103c2.svg';
  static const String twitter2 = 'assets/images/fd25bdd0b40b.svg';
  static const String vector22 = 'assets/images/74d132cba9ee.svg';
  static const String vector24 = 'assets/images/c9d4470d5a8e.svg';
  static const String youtube2 = 'assets/images/33ebb553387d.svg';
}
