import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import 'f2f_support.dart';

import 'package:flutter_svg/flutter_svg.dart';

import 'assets.dart';
import 'colors.dart';

// Auto-generated by figma2flutter. Verify against screenshot.
// designSize: 375.0 x 3333.0
class CategoryGridViewFull extends StatelessWidget {
  const CategoryGridViewFull({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: FashionAppColors.cFFFFFFFF,
      body: SingleChildScrollView(
        padding: EdgeInsets.only(
          bottom: MediaQuery.viewPaddingOf(context).bottom,
        ),
        child: Container(
          width: 375.0.w,
          decoration: BoxDecoration(color: FashionAppColors.cFFFFFFFF),
          child: Padding(
            padding: EdgeInsets.only(top: 5.0.w),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                SvgPicture.asset(FashionAppAssets.header2, width: 375.0.w),
                SizedBox(height: 12.0.w),
                Padding(
                  padding: EdgeInsets.only(
                    left: 15.75.w,
                    top: 1.89.w,
                    bottom: 11.0.w,
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          SizedBox(
                            width: 343.25.w,
                            child: Row(
                              mainAxisSize: MainAxisSize.max,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                Text(
                                  '4500 APPAREL',
                                  style: gf(
                                    'Tenor Sans',
                                    fontSize: 14.0.sp,
                                    fontWeight: FontWeight.w400,
                                    color: FashionAppColors.cFF333333,
                                    letterSpacing: 0.0.w,
                                    height: 1.06,
                                  ),
                                  textAlign: TextAlign.center,
                                  maxLines: 1,
                                ),
                                const Spacer(),
                                InkWell(
                                  onTap: () {}, // TODO: wire 'new'
                                  borderRadius: BorderRadius.circular(33.0.w),
                                  child: Container(
                                    width: 72.75.w,
                                    constraints: BoxConstraints(
                                      minHeight: 36.0.w,
                                    ),
                                    decoration: BoxDecoration(
                                      color: FashionAppColors.cFFC4C4C4,
                                      borderRadius: BorderRadius.circular(
                                        33.0.w,
                                      ),
                                    ),
                                    child: Padding(
                                      padding: EdgeInsets.only(
                                        left: 15.53.w,
                                        top: 9.21.w,
                                        bottom: 10.72.w,
                                      ),
                                      child: Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        mainAxisSize: MainAxisSize.min,
                                        children: [
                                          Row(
                                            mainAxisSize: MainAxisSize.min,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.center,
                                            children: [
                                              Flexible(
                                                child: Text(
                                                  'New',
                                                  style: gf(
                                                    'Tenor Sans',
                                                    fontSize: 13.0.sp,
                                                    fontWeight: FontWeight.w400,
                                                    color: FashionAppColors.cFF555555,
                                                    letterSpacing: 0.0.w,
                                                    height: 1.06,
                                                  ),
                                                  textAlign: TextAlign.center,
                                                ),
                                              ),
                                              SizedBox(width: 2.9.w),
                                              SvgPicture.asset(
                                                FashionAppAssets.down,
                                                width: 16.07.w,
                                                height: 16.07.w,
                                                fit: BoxFit.contain,
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ),
                                SizedBox(width: 8.0.w),
                                Container(
                                  width: 36.0.w,
                                  constraints: BoxConstraints(
                                    minHeight: 36.0.w,
                                  ),
                                  decoration: BoxDecoration(
                                    color: FashionAppColors.cFFC4C4C4,
                                    borderRadius: BorderRadius.circular(18.0.w),
                                  ),
                                  clipBehavior: Clip.antiAlias,
                                  child: ConstrainedBox(
                                    constraints: BoxConstraints(
                                      minHeight: 36.0.w,
                                    ),
                                    child: Center(
                                      child: FittedBox(
                                        fit: BoxFit.scaleDown,
                                        child: SvgPicture.asset(
                                          FashionAppAssets.gallery,
                                          width: 20.0.w,
                                          height: 20.0.w,
                                          fit: BoxFit.contain,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                                SizedBox(width: 9.0.w),
                                Container(
                                  width: 36.0.w,
                                  constraints: BoxConstraints(
                                    minHeight: 36.0.w,
                                  ),
                                  decoration: BoxDecoration(
                                    color: FashionAppColors.cFFC4C4C4,
                                    borderRadius: BorderRadius.circular(18.0.w),
                                  ),
                                  clipBehavior: Clip.antiAlias,
                                  child: Padding(
                                    padding: EdgeInsets.only(
                                      left: 8.0.w,
                                      top: 10.0.w,
                                      bottom: 6.0.w,
                                    ),
                                    child: Column(
                                      crossAxisAlignment:
                                          CrossAxisAlignment.start,
                                      mainAxisSize: MainAxisSize.min,
                                      children: [
                                        SvgPicture.asset(
                                          FashionAppAssets.filter,
                                          width: 20.0.w,
                                          height: 20.0.w,
                                          fit: BoxFit.contain,
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                      SizedBox(height: 13.89.w),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          InkWell(
                            onTap: () {}, // TODO: wire 'women'
                            borderRadius: BorderRadius.circular(30.0.w),
                            child: Wrap(
                              spacing: 8.0.w,
                              runSpacing: 8.0.w,
                              children: [
                                _tag(_tagData[0], 0),
                                _tag(_tagData[1], 1),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                SizedBox(height: 5.0.w),
                Padding(
                  padding: EdgeInsets.only(left: 16.0.w, right: 15.0.w),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      SizedBox(
                        width: 343.0.w,
                        child: ListView.builder(
                          shrinkWrap: true,
                          physics: const NeverScrollableScrollPhysics(),
                          padding: EdgeInsets.zero,
                          itemCount: _productData.length,
                          itemBuilder: (context, index) => Padding(
                            padding: EdgeInsets.only(
                              bottom: index == _productData.length - 1
                                  ? 0.0
                                  : 24.98.w,
                            ),
                            child: _product(_productData[index], index),
                          ),
                        ),
                      ),
                      SizedBox(height: 82.47.w),
                      Padding(
                        padding: EdgeInsets.only(left: 61.51.w),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Row(
                              mainAxisSize: MainAxisSize.min,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                F2FPinInput(
                                  length: 5,
                                  boxWidth: 32.0.w,
                                  boxHeight: 32.0.w,
                                  gap: 12.0.w,
                                  radius: 14.0.w,
                                  fill: FashionAppColors.cFFFFFFFF,
                                  textColor: FashionAppColors.cFF555555,
                                  textSize: 16.0.sp,
                                  activeColor: FashionAppColors.cFFC4C4C4,
                                  initial: '12345',
                                ),
                                SizedBox(width: 9.05.w),
                                SvgPicture.asset(
                                  FashionAppAssets.forward,
                                  width: 24.0.w,
                                  height: 24.0.w,
                                  fit: BoxFit.contain,
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                SizedBox(height: 23.0.w),
                Container(
                  width: 375.0.w,
                  constraints: BoxConstraints(minHeight: 340.0.w),
                  decoration: BoxDecoration(color: FashionAppColors.cFFFFFFFF),
                  child: Padding(
                    padding: EdgeInsets.only(top: 23.78.w),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Padding(
                          padding: EdgeInsets.only(left: 106.5.w),
                          child: SizedBox(
                            width: 162.0.w,
                            child: Row(
                              mainAxisSize: MainAxisSize.max,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                SvgPicture.asset(
                                  FashionAppAssets.twitter2,
                                  width: 24.0.w,
                                  height: 24.0.w,
                                  fit: BoxFit.contain,
                                ),
                                const Spacer(),
                                SvgPicture.asset(
                                  FashionAppAssets.instagram3,
                                  width: 24.0.w,
                                  height: 24.0.w,
                                  fit: BoxFit.contain,
                                ),
                                const Spacer(),
                                SvgPicture.asset(
                                  FashionAppAssets.youtube2,
                                  width: 24.0.w,
                                  height: 24.0.w,
                                  fit: BoxFit.contain,
                                ),
                              ],
                            ),
                          ),
                        ),
                        SizedBox(height: 24.0.w),
                        Padding(
                          padding: EdgeInsets.only(left: 125.02.w),
                          child: SizedBox(
                            width: 124.96.w,
                            height: 9.25.w,
                            child: OverflowBox(
                              minWidth: 0,
                              minHeight: 0,
                              maxWidth: 125.0.w,
                              maxHeight: 10.0.w,
                              alignment: Alignment.topLeft,
                              child: Transform.translate(
                                offset: Offset(-0.0.w, -0.0.w),
                                child: SvgPicture.asset(
                                  FashionAppAssets.a5,
                                  width: 125.0.w,
                                  height: 10.0.w,
                                ),
                              ),
                            ),
                          ),
                        ),
                        SizedBox(height: 18.73.w),
                        Padding(
                          padding: EdgeInsets.only(left: 95.0.w),
                          child: SizedBox(
                            width: 184.0.w,
                            height: 116.02.w,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0.0.w,
                                  top: 0.0.w,
                                  child: SizedBox(
                                    width: 202.4.w,
                                    child: Text(
                                      'support@openui.design\n+60 825 876\n08:00 - 22:00 - Everyday',
                                      style: gf(
                                        'Inter',
                                        fontSize: 16.0.sp,
                                        fontWeight: FontWeight.w400,
                                        color: FashionAppColors.cFF333333,
                                        letterSpacing: 0.0.w,
                                        height: 1.84,
                                      ),
                                      textAlign: TextAlign.center,
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 30.02.w,
                                  top: 106.76.w,
                                  child: SizedBox(
                                    width: 124.96.w,
                                    height: 9.25.w,
                                    child: OverflowBox(
                                      minWidth: 0,
                                      minHeight: 0,
                                      maxWidth: 125.0.w,
                                      maxHeight: 10.0.w,
                                      alignment: Alignment.topLeft,
                                      child: Transform.translate(
                                        offset: Offset(-0.0.w, -0.0.w),
                                        child: SvgPicture.asset(
                                          FashionAppAssets.a5,
                                          width: 125.0.w,
                                          height: 10.0.w,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        SizedBox(height: 32.0.w),
                        Padding(
                          padding: EdgeInsets.only(left: 58.0.w),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Flexible(
                                child: Text(
                                  'About',
                                  style: gf(
                                    'Inter',
                                    fontSize: 16.0.sp,
                                    fontWeight: FontWeight.w400,
                                    color: FashionAppColors.cFF000000,
                                    letterSpacing: 0.0.w,
                                    height: 1.5,
                                  ),
                                  textAlign: TextAlign.center,
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                              SizedBox(width: 52.0.w),
                              Flexible(
                                child: Text(
                                  'Contact',
                                  style: gf(
                                    'Inter',
                                    fontSize: 16.0.sp,
                                    fontWeight: FontWeight.w400,
                                    color: FashionAppColors.cFF000000,
                                    letterSpacing: 0.0.w,
                                    height: 1.5,
                                  ),
                                  textAlign: TextAlign.center,
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                              SizedBox(width: 52.0.w),
                              Flexible(
                                child: Text(
                                  'Blog',
                                  style: gf(
                                    'Inter',
                                    fontSize: 16.0.sp,
                                    fontWeight: FontWeight.w400,
                                    color: FashionAppColors.cFF000000,
                                    letterSpacing: 0.0.w,
                                    height: 1.5,
                                  ),
                                  textAlign: TextAlign.center,
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                            ],
                          ),
                        ),
                        SizedBox(height: 22.97.w),
                        InkWell(
                          onTap: () {}, // TODO: wire 'copyrightOpenuiAllRights'
                          child: Container(
                            width: 375.0.w,
                            height: 45.25.w,
                            decoration: BoxDecoration(color: FashionAppColors.cFFC4C4C4),
                            child: Padding(
                              padding: EdgeInsets.only(
                                top: 11.07.w,
                                bottom: 15.18.w,
                              ),
                              child: Center(
                                child: Text(
                                  'Copyright© OpenUI All Rights Reserved.',
                                  style: gf(
                                    'Inter',
                                    fontSize: 12.0.sp,
                                    fontWeight: FontWeight.w400,
                                    color: FashionAppColors.cFF555555,
                                    letterSpacing: 0.0.w,
                                    height: 1.58,
                                  ),
                                  textAlign: TextAlign.center,
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  /// Extracted from Tag — 2 instances in the design.
  Widget _tag(Map<String, String> d, int index) {
    return InkWell(
      onTap: () {}, // TODO: wire 'women.$index'
      borderRadius: BorderRadius.circular(30.0.w),
      child: Container(
        constraints: BoxConstraints(minHeight: 32.0.w),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0.w),
          border: Border.all(
            color: FashionAppColors.cFFDEDEDE,
            width: 1.0.w,
            strokeAlign: BorderSide.strokeAlignOutside,
          ),
        ),
        child: Padding(
          padding: EdgeInsets.only(
            left: 10.0.w,
            top: 8.0.w,
            right: 10.0.w,
            bottom: 8.0.w,
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Row(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Flexible(
                    child: Text(
                      d['text'] ?? '',
                      style: gf(
                        'Inter',
                        fontSize: 14.0.sp,
                        fontWeight: FontWeight.w400,
                        color: FashionAppColors.cFF333333,
                        letterSpacing: 0.14.w,
                        height: 1.14,
                      ),
                      textAlign: TextAlign.center,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                  SizedBox(width: 6.0.w),
                  SvgPicture.asset(
                    FashionAppAssets.close,
                    width: 16.0.w,
                    height: 16.0.w,
                    fit: BoxFit.contain,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  /// Extracted from Product — 5 instances in the design.
  Widget _product(Map<String, String> d, int index) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: [
        SizedBox(
          width: 343.0.w,
          height: 457.33.w,
          child: Stack(
            children: [
              Positioned(
                left: 0.0.w,
                top: 0.0.w,
                child: Image.asset(
                  d['image'] ?? '',
                  width: 343.0.w,
                  height: 457.33.w,
                  fit: BoxFit.cover,
                ),
              ),
              Positioned(
                left: 312.0.w,
                top: 428.2.w,
                child: SvgPicture.asset(
                  d['heart'] ?? '',
                  width: 16.0.w,
                  height: 16.0.w,
                  fit: BoxFit.contain,
                ),
              ),
            ],
          ),
        ),
        SizedBox(height: 1.67.w),
        Text(
          'MOHAN',
          style: gf(
            'Inter',
            fontSize: 18.0.sp,
            fontWeight: FontWeight.w400,
            color: FashionAppColors.cFF000000,
            letterSpacing: 4.0.w,
            height: 2.22,
          ),
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
        ),
        SizedBox(
          width: 342.52.w,
          child: Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Flexible(
                flex: 268,
                child: Text(
                  'Recycle Boucle Knit Cardigan Pink',
                  style: gf(
                    'Tenor Sans',
                    fontSize: 16.0.sp,
                    fontWeight: FontWeight.w400,
                    color: FashionAppColors.cFF555555,
                    letterSpacing: 0.0.w,
                    height: 1.5,
                  ),
                  textAlign: TextAlign.center,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
              Text(
                '\$120',
                style: gf(
                  'Tenor Sans',
                  fontSize: 18.0.sp,
                  fontWeight: FontWeight.w400,
                  color: FashionAppColors.cFFDD8560,
                  letterSpacing: 0.0.w,
                  height: 0.78,
                ),
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
            ],
          ),
        ),
      ],
    );
  }
}

const _tagData = <Map<String, String>>[
  {'text': 'Women'},
  {'text': 'All apparel'},
];

const _productData = <Map<String, String>>[
  {
    'image': 'assets/images/de4f87dd9433.png',
    'heart': 'assets/images/c85a4420a149.svg',
  },
  {
    'image': 'assets/images/30dfc4368f15.png',
    'heart': 'assets/images/c8e393cb5a5f.svg',
  },
  {
    'image': 'assets/images/3671abb4fe66.png',
    'heart': 'assets/images/c8e393cb5a5f.svg',
  },
  {
    'image': 'assets/images/915df442a8b8.png',
    'heart': 'assets/images/7822d1f80238.svg',
  },
  {
    'image': 'assets/images/f6fda6b0c519.png',
    'heart': 'assets/images/7822d1f80238.svg',
  },
];