// GENERATED by figma2flutter — shared colour tokens. Do not edit by hand.
// Project 'fashion_app': colours used on >= 2 screens = one source of truth.
import 'package:flutter/material.dart';

class FashionAppColors {
  FashionAppColors._();
  static const Color c66000000 = Color(0x66000000);
  static const Color cFF000000 = Color(0xFF000000);
  static const Color cFF333333 = Color(0xFF333333);
  static const Color cFF555555 = Color(0xFF555555);
  static const Color cFFC4C4C4 = Color(0xFFC4C4C4);
  static const Color cFFDD8560 = Color(0xFFDD8560);
  static const Color cFFDEDEDE = Color(0xFFDEDEDE);
  static const Color cFFF9F9F9 = Color(0xFFF9F9F9);
  static const Color cFFFCFCFC = Color(0xFFFCFCFC);
  static const Color cFFFFFFFF = Color(0xFFFFFFFF);
}
