// Auto-generated by figma2flutter. Shared by every generated screen.
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:google_fonts/google_fonts.dart';

// Re-exported so a generated screen needs only this one import (its ThemeData
// still references GoogleFonts directly for textTheme).
export 'package:google_fonts/google_fonts.dart';

/// The per-screen chrome every generated screen shares, in ONE place instead of
/// repeated in every file:
///  * text scaling locked to 1.0, so the device font-size setting can't reflow a
///    pixel-matched layout;
///  * `TextHeightBehavior(leadingDistribution: even)` as the DEFAULT, so glyphs
///    sit centred in their line box (matching Figma) without every `Text`
///    carrying the same three lines;
///  * the project [ThemeData], when the screen passes one.
class F2FScreen extends StatelessWidget {
  const F2FScreen({super.key, required this.child, this.theme});

  final Widget child;
  final ThemeData? theme;

  @override
  Widget build(BuildContext context) {
    Widget out = DefaultTextHeightBehavior(
      textHeightBehavior: const TextHeightBehavior(
          leadingDistribution: TextLeadingDistribution.even),
      child: child,
    );
    if (theme != null) out = Theme(data: theme!, child: out);
    return MediaQuery.withClampedTextScaling(
        minScaleFactor: 1.0, maxScaleFactor: 1.0, child: out);
  }
}

/// Render an asset chosen by its extension — SVG via flutter_svg, otherwise a
/// raster Image. An extracted item builder can carry a per-instance asset path
/// that is EITHER a .svg or a .png (a tile grid mixes a rasterised-to-PNG icon
/// with an SVG one), so the widget KIND must be decided at runtime, not baked
/// from the prototype. An empty path renders a same-size blank.
Widget f2fAsset(String path,
    {double? width, double? height, BoxFit fit = BoxFit.contain}) {
  if (path.isEmpty) return SizedBox(width: width, height: height);
  return path.toLowerCase().endsWith('.svg')
      ? SvgPicture.asset(path, width: width, height: height, fit: fit)
      : Image.asset(path, width: width, height: height, fit: fit);
}

/// Resolve a Google font, falling back to Inter when the family isn't on Google
/// Fonts — so an unknown family (e.g. "SF Pro") never breaks the build.
/// Fonts that are NOT a design choice — they are what Figma falls back to when
/// a glyph is missing from the real family, and Google Fonts has none of them.
/// home_2's filter chips carry their icons as EMOJI TEXT ("⚡" in FreeSans,
/// "📍" in Liberation Sans), so naming the family drew two tofu boxes instead of
/// the icons. Dropping the family lets the platform's own emoji font render
/// them. Keep this list to substitutes only; a real family must never land here.
const Set<String> _kSubstituteFamilies = {
  'FreeSans',
  'Liberation Sans',
  'DejaVu Sans',
  'Noto Color Emoji',
  'Segoe UI Emoji',
  'Apple Color Emoji',
};

TextStyle gf(String family,
    {double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    Color? color,
    double? letterSpacing,
    double? height,
    TextDecoration? decoration,
    Color? decorationColor,
    Paint? foreground}) {
  // `color` and `foreground` are mutually exclusive in TextStyle; the emitter
  // only ever passes one (foreground for gradient-filled glyphs, color
  // otherwise), so pass whichever is set.
  //
  // When runtime fetching is OFF (only the golden capture test sets that; the
  // real app leaves it ON), GoogleFonts.getFont returns a style whose font loads
  // ASYNCHRONOUSLY and then THROWS post-frame if the .ttf isn't bundled — an
  // uncaught async error that failed every capture even though the golden PNG was
  // already written (a sync try/catch can't catch it). Skip google_fonts here and
  // return a plain TextStyle naming the family directly. Naming it MATTERS: with
  // no `fontFamily`, flutter_test draws every glyph in its own fixed-width block
  // font far wider than Inter, so every width-overflow number the render sweep
  // reported was inflated and unusable. A host that bundles the family (the
  // harness declares Inter/Manrope/Poppins/Playfair Display) now measures with
  // the REAL metrics; an unbundled family falls back exactly as before.
  if (_kSubstituteFamilies.contains(family)) {
    return TextStyle(
        fontSize: fontSize,
        fontWeight: fontWeight,
        fontStyle: fontStyle,
        color: foreground == null ? color : null,
        foreground: foreground,
        letterSpacing: letterSpacing,
        height: height,
        decoration: decoration,
        decorationColor: decorationColor);
  }
  if (!GoogleFonts.config.allowRuntimeFetching) {
    return TextStyle(
        fontFamily: family,
        fontSize: fontSize,
        fontWeight: fontWeight,
        fontStyle: fontStyle,
        color: foreground == null ? color : null,
        foreground: foreground,
        letterSpacing: letterSpacing,
        height: height,
        decoration: decoration,
        decorationColor: decorationColor);
  }
  try {
    return GoogleFonts.getFont(family,
        fontSize: fontSize,
        fontWeight: fontWeight,
        fontStyle: fontStyle,
        color: foreground == null ? color : null,
        foreground: foreground,
        letterSpacing: letterSpacing,
        height: height,
        decoration: decoration,
        decorationColor: decorationColor);
  } catch (_) {
    return GoogleFonts.inter(
        fontSize: fontSize,
        fontWeight: fontWeight,
        fontStyle: fontStyle,
        color: foreground == null ? color : null,
        foreground: foreground,
        letterSpacing: letterSpacing,
        height: height,
        decoration: decoration,
        decorationColor: decorationColor);
  }
}

/// Paints a dashed/dotted rounded-rect border (Figma dashPattern) on top of a
/// box — BoxDecoration has no dashed-border support. The stroke is centred on
/// the box edge, inset by half its width so it stays inside the box.
/// Paints a box's drop shadows OUTSIDE its shape only.
///
/// `BoxDecoration.boxShadow` draws the full blurred rounded-rect behind the
/// box, so a box with a TRANSLUCENT fill lets its own shadow tint its interior.
/// Figma does not do that — its drop shadow reads as light cast around the
/// shape — so a white-at-20% pill over a white page renders pure white there
/// and grey here. This clips the shape out and paints the same shadows into
/// what is left, which matches Figma and leaves opaque boxes untouched (they
/// keep using `boxShadow`, where the knockout would be invisible anyway).
class F2FOuterShadow extends StatelessWidget {
  const F2FOuterShadow(
      {super.key,
      required this.borderRadius,
      required this.boxShadow,
      required this.child});

  final BorderRadius borderRadius;
  final List<BoxShadow> boxShadow;
  final Widget child;

  @override
  Widget build(BuildContext context) => CustomPaint(
        painter: _F2FOuterShadowPainter(borderRadius, boxShadow),
        child: child,
      );
}

class _F2FOuterShadowPainter extends CustomPainter {
  const _F2FOuterShadowPainter(this.radius, this.shadows);

  final BorderRadius radius;
  final List<BoxShadow> shadows;

  @override
  void paint(Canvas canvas, Size size) {
    if (shadows.isEmpty) return;
    final rect = Offset.zero & size;
    final shape = Path()..addRRect(radius.toRRect(rect));
    // Room for the widest shadow to spill; anything past it is clipped by the
    // layer above anyway.
    var pad = 0.0;
    for (final s in shadows) {
      final reach = s.blurRadius +
          s.spreadRadius.abs() +
          s.offset.dx.abs() +
          s.offset.dy.abs();
      if (reach > pad) pad = reach;
    }
    // Paint the shadows into their own layer, then ERASE the shape from it.
    // The old difference-path clip was right under flutter_test's Skia but
    // the web renderer painted the shadow INSIDE the shape anyway, so every
    // translucent card in a web preview had a grey core (desynq-mq62d's glass
    // bottom bar: white in Figma, rgb(229,225,225) on the web).
    canvas.saveLayer(rect.inflate(pad + 8), Paint());
    for (final s in shadows) {
      final rr = radius
          .toRRect(rect.shift(s.offset).inflate(s.spreadRadius));
      canvas.drawRRect(
          rr,
          Paint()
            ..color = s.color
            ..maskFilter = MaskFilter.blur(BlurStyle.normal, s.blurSigma));
    }
    canvas.drawPath(shape, Paint()..blendMode = BlendMode.clear);
    canvas.restore();
  }

  @override
  bool shouldRepaint(_F2FOuterShadowPainter old) =>
      old.radius != radius || old.shadows != shadows;
}

class F2FDashedBorder extends CustomPainter {
  const F2FDashedBorder(
      {required this.color,
      required this.strokeWidth,
      required this.radius,
      required this.dash});
  final Color color;
  final double strokeWidth;
  final double radius;
  final List<double> dash;
  @override
  void paint(Canvas canvas, Size size) {
    final inset = strokeWidth / 2;
    final rect = Rect.fromLTWH(
        inset, inset, size.width - strokeWidth, size.height - strokeWidth);
    final src = Path()
      ..addRRect(RRect.fromRectAndRadius(rect, Radius.circular(radius)));
    final paint = Paint()
      ..color = color
      ..strokeWidth = strokeWidth
      ..style = PaintingStyle.stroke;
    final on = dash.isNotEmpty ? dash[0] : 4.0;
    final off = dash.length > 1 ? dash[1] : on;
    for (final metric in src.computeMetrics()) {
      var d = 0.0;
      while (d < metric.length) {
        final len = (d + on < metric.length) ? on : metric.length - d;
        canvas.drawPath(metric.extractPath(d, d + len), paint);
        d += on + off;
      }
    }
  }

  @override
  bool shouldRepaint(F2FDashedBorder old) =>
      old.color != color ||
      old.strokeWidth != strokeWidth ||
      old.radius != radius ||
      old.dash != dash;
}

/// Strokes a rounded-rect border with a linear-gradient shader — for a Figma
/// gradient-border box that has NO fill, so the real background shows through
/// the transparent centre (a filled gradient box can't: its centre would carry
/// the whole gradient). Foreground so the rim sits on top of the child content.
class F2FGradientBorder extends CustomPainter {
  const F2FGradientBorder(
      {required this.colors,
      required this.stops,
      required this.begin,
      required this.end,
      required this.strokeWidth,
      required this.radius});
  final List<Color> colors;
  final List<double> stops;
  final Alignment begin;
  final Alignment end;
  final double strokeWidth;
  final double radius;
  @override
  void paint(Canvas canvas, Size size) {
    final inset = strokeWidth / 2;
    final rect = Rect.fromLTWH(
        inset, inset, size.width - strokeWidth, size.height - strokeWidth);
    final rr = (radius - inset).clamp(0.0, radius);
    final shader = LinearGradient(colors: colors, stops: stops, begin: begin, end: end)
        .createShader(Offset.zero & size);
    final paint = Paint()
      ..shader = shader
      ..strokeWidth = strokeWidth
      ..style = PaintingStyle.stroke;
    canvas.drawRRect(
        RRect.fromRectAndRadius(rect, Radius.circular(rr)), paint);
  }

  @override
  bool shouldRepaint(F2FGradientBorder old) =>
      old.colors != colors ||
      old.stops != stops ||
      old.begin != begin ||
      old.end != end ||
      old.strokeWidth != strokeWidth ||
      old.radius != radius;
}

/// Clips an overhanging asset in a Stack to a covering card's rounded rect: the
/// two BOTTOM corners follow the card radius while the TOP is left open, so an
/// asset that also bleeds ABOVE the card (help_support's woman photo poking over
/// the Hero Banner) keeps its head. [left]/[right]/[bottom] are the card's edges
/// in the child's own coordinate space.
class F2FCardClip extends CustomClipper<Path> {
  const F2FCardClip(this.left, this.right, this.bottom, this.radius);
  final double left, right, bottom, radius;
  @override
  Path getClip(Size size) {
    final r = Radius.circular(radius);
    return Path()
      ..addRRect(RRect.fromLTRBAndCorners(left, -10000, right, bottom,
          bottomLeft: r, bottomRight: r));
  }

  @override
  bool shouldReclip(F2FCardClip old) =>
      old.left != left ||
      old.right != right ||
      old.bottom != bottom ||
      old.radius != radius;
}

/// A real, toggleable Material checkbox that reproduces the Figma design's drawn
/// checkbox (a rounded square + a tick) pixel-close, so the exported SVG can be
/// dropped and the user gets a genuine, accessible, tappable widget instead of a
/// static image — the same play as the drawable-shape passes. Self-contained
/// state so a screen need not become a StatefulWidget just to hold a tick.
class F2FCheckbox extends StatefulWidget {
  const F2FCheckbox(
      {super.key, this.initial = false, required this.color, this.size = 20});
  final bool initial;
  final Color color;
  final double size;
  @override
  State<F2FCheckbox> createState() => _F2FCheckboxState();
}

class _F2FCheckboxState extends State<F2FCheckbox> {
  late bool _v = widget.initial;
  @override
  Widget build(BuildContext context) {
    // Paints the EXACT Figma checkbox — a rounded square (r4 in a 20-unit box)
    // plus the designed 3-point tick — instead of Material's Checkbox, whose tick
    // curvature and corner radius read differently from the export.
    return GestureDetector(
      onTap: () => setState(() => _v = !_v),
      behavior: HitTestBehavior.opaque,
      child: CustomPaint(
        size: Size(widget.size, widget.size),
        painter: _F2FCheckPainter(_v, widget.color),
      ),
    );
  }
}

class _F2FCheckPainter extends CustomPainter {
  _F2FCheckPainter(this.checked, this.color);
  final bool checked;
  final Color color;
  @override
  void paint(Canvas canvas, Size size) {
    final s = size.width / 20.0; // Figma box is 20 units wide
    final box = RRect.fromRectAndRadius(Offset.zero & size, Radius.circular(4 * s));
    if (checked) {
      canvas.drawRRect(box, Paint()..color = color);
      final tick = Path()
        ..moveTo(14.3334 * s, 6.75 * s)
        ..lineTo(8.37508 * s, 12.7083 * s)
        ..lineTo(5.66675 * s, 10 * s);
      canvas.drawPath(
          tick,
          Paint()
            ..color = const Color(0xFFFFFFFF)
            ..style = PaintingStyle.stroke
            ..strokeWidth = 1.08333 * s
            ..strokeCap = StrokeCap.round
            ..strokeJoin = StrokeJoin.round);
    } else {
      canvas.drawRRect(
          box,
          Paint()
            ..color = color.withValues(alpha: 0.55)
            ..style = PaintingStyle.stroke
            ..strokeWidth = 1.5 * s);
    }
  }

  @override
  bool shouldRepaint(_F2FCheckPainter old) =>
      old.checked != checked || old.color != color;
}

/// A real, typeable OTP/PIN row: [length] boxes drawn to match the Figma design
/// (fill + soft shadow, the active box outlined in the accent) over a hidden
/// digit TextField. Prefilled with the example digits Figma showed, but editable.
class F2FPinInput extends StatefulWidget {
  const F2FPinInput(
      {super.key,
      this.length = 4,
      required this.boxWidth,
      required this.boxHeight,
      required this.gap,
      required this.radius,
      required this.fill,
      required this.textColor,
      required this.textSize,
      required this.activeColor,
      this.borderColor,
      this.borderWidth,
      this.initial = ''});
  final int length;
  final double boxWidth, boxHeight, gap, radius, textSize;
  final Color fill, textColor, activeColor;
  /// The box's real Figma stroke. Null when Figma drew none, in which case the
  /// faint default below stands in so an empty box still reads as a box.
  final Color? borderColor;
  final double? borderWidth;
  final String initial;
  @override
  State<F2FPinInput> createState() => _F2FPinInputState();
}

class _F2FPinInputState extends State<F2FPinInput> {
  late final TextEditingController _c =
      TextEditingController(text: widget.initial);
  final FocusNode _f = FocusNode();
  @override
  void dispose() {
    _c.dispose();
    _f.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => _f.requestFocus(),
      behavior: HitTestBehavior.opaque,
      child: Stack(
        children: [
          AnimatedBuilder(
            animation: _c,
            builder: (context, _) {
              final text = _c.text;
              final active = text.length < widget.length ? text.length : -1;
              return Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  for (var i = 0; i < widget.length; i++) ...[
                    if (i > 0) SizedBox(width: widget.gap),
                    Builder(builder: (context) {
                      final filled = i < text.length;
                      return Container(
                        width: widget.boxWidth,
                        height: widget.boxHeight,
                        alignment: Alignment.center,
                        decoration: BoxDecoration(
                          color: widget.fill,
                          borderRadius: BorderRadius.circular(widget.radius),
                          // When Figma gave us the box's real stroke, draw it
                          // on EVERY box — Figma strokes the filled ones too
                          // (callforjobs/railcab export the rim on exactly the
                          // filled boxes). When it did not, fall back to the old
                          // behaviour and rim only the empty ones: inventing a
                          // rim on a filled box measurably moved vynoc and
                          // salarient AWAY from their Figma reference.
                          // strokeAlign is explicit and INSIDE to match `_box`:
                          // the rim must not grow the fixed boxWidth/boxHeight.
                          border: (widget.borderColor == null &&
                                  filled &&
                                  i != active)
                              ? null
                              : Border.all(
                                  color: i == active
                                      ? widget.activeColor
                                      : (widget.borderColor ??
                                          const Color(0x22000000)),
                                  // With a real Figma rim the focused box just
                                  // thickens it; with no rim keep the exact old
                                  // 1.6/1.2 so a screen Figma never stroked
                                  // renders byte-identical to before this change.
                                  width: i == active
                                      ? (widget.borderWidth == null
                                          ? 1.6
                                          : widget.borderWidth! * 1.35)
                                      : (widget.borderWidth ?? 1.2),
                                  strokeAlign: BorderSide.strokeAlignInside,
                                ),
                          boxShadow: const [
                            BoxShadow(
                                color: Color(0x0F000000),
                                blurRadius: 8,
                                offset: Offset(0, 2))
                          ],
                        ),
                        child: Text(
                          filled ? text[i] : '–', // en-dash placeholder
                          style: TextStyle(
                              color: filled
                                  ? widget.textColor
                                  : const Color(0x66000000),
                              fontSize: widget.textSize,
                              fontWeight: FontWeight.w700),
                        ),
                      );
                    }),
                  ],
                ],
              );
            },
          ),
          Positioned.fill(
            child: Opacity(
              opacity: 0,
              child: TextField(
                controller: _c,
                focusNode: _f,
                keyboardType: TextInputType.number,
                maxLength: widget.length,
                showCursor: false,
                enableInteractiveSelection: false,
                inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                decoration: const InputDecoration(
                    counterText: '', border: InputBorder.none),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// A tappable date field that reproduces a Figma date pill: it shows the hint
/// until a date is picked, then the chosen date (d/M/y). Tapping opens the
/// Material date picker. Self-contained state so the pill/calendar icon the
/// designer drew is untouched and the screen needn't own a controller for it.
class F2FDateField extends StatefulWidget {
  const F2FDateField({super.key, required this.hint, required this.style});
  final String hint;
  final TextStyle style;
  @override
  State<F2FDateField> createState() => _F2FDateFieldState();
}

class _F2FDateFieldState extends State<F2FDateField> {
  DateTime? _v;
  @override
  Widget build(BuildContext context) {
    final label =
        _v == null ? widget.hint : '${_v!.day}/${_v!.month}/${_v!.year}';
    return GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: () async {
        final now = DateTime.now();
        final picked = await showDatePicker(
          context: context,
          initialDate: _v ?? DateTime(now.year - 18, now.month, now.day),
          firstDate: DateTime(1900),
          lastDate: now,
        );
        if (picked != null) setState(() => _v = picked);
      },
      child: Text(label,
          style: widget.style, maxLines: 1, overflow: TextOverflow.ellipsis),
    );
  }
}

/// A real DropdownButton behind a Figma dropdown pill. The drawn chevron stays
/// (the button's own icon/underline are stripped), so only the placeholder Text
/// is swapped for a genuine selectable control. Figma carries no option data,
/// so [items] is a stub the host app replaces.
class F2FDropdown extends StatefulWidget {
  const F2FDropdown(
      {super.key, required this.hint, required this.items, required this.style});
  final String hint;
  final List<String> items;
  final TextStyle style;
  @override
  State<F2FDropdown> createState() => _F2FDropdownState();
}

class _F2FDropdownState extends State<F2FDropdown> {
  String? _v;
  @override
  Widget build(BuildContext context) {
    return DropdownButton<String>(
      value: _v,
      hint: Text(widget.hint, style: widget.style, overflow: TextOverflow.ellipsis),
      isDense: true,
      isExpanded: false,
      underline: const SizedBox.shrink(),
      icon: const SizedBox.shrink(),
      style: widget.style,
      items: widget.items
          .map((e) => DropdownMenuItem(
              value: e,
              child: Text(e, style: widget.style, overflow: TextOverflow.ellipsis)))
          .toList(),
      onChanged: (x) => setState(() => _v = x),
    );
  }
}

/// One destination for [F2FBottomNavScaffold]: a label, an optional icon asset,
/// and the page shown when the tab is selected.
class F2FNavItem {
  const F2FNavItem(
      {required this.label,
      this.icon,
      this.activeIcon,
      required this.page,
      this.center = false,
      this.fabColor,
      this.fabSize = 0});
  final String label;
  final String? icon; // inactive/default asset (svg/png); null -> no icon
  /// Filled/selected-state icon, harvested from the merged screen where THIS tab
  /// was the active one. Shown when the tab is selected; falls back to [icon]
  /// when the design has no separate filled variant.
  final String? activeIcon;
  final Widget page; // real body, or a Center(Text(label)) placeholder
  /// An elevated CENTER action button (home's green "Tree"): a filled circle
  /// lifted above the bar rather than a flat tab.
  final bool center;
  final Color? fabColor;
  final double fabSize;
}

/// Merges N single-screen exports that share one bottom-nav bar into ONE app
/// shell: an [IndexedStack] of the per-tab bodies driven by a hand-built bar.
/// A CUSTOM bar (not Material's BottomNavigationBar) so the design's exact
/// styling — colours, the top indicator on the active tab — is reproduced.
/// Owns the selected index itself, so the merged screen stays a one-liner.
class F2FBottomNavScaffold extends StatefulWidget {
  const F2FBottomNavScaffold({
    super.key,
    required this.items,
    this.initialIndex = 0,
    this.barColor = Colors.white,
    this.activeColor = const Color(0xFF212121),
    this.inactiveColor = const Color(0xFF797979),
    // NULL = the design has NO active-tab indicator rectangle (RailCab marks the
    // active tab by a filled icon + bold label only). Draw the top bar ONLY when
    // Figma actually had one (campus). A non-null default here used to paint a
    // phantom indigo bar on bars that never had an indicator.
    this.indicatorColor,
    this.fontFamily = 'Inter',
    this.fontSize = 12,
    // Exact Figma geometry (offsets from the bar's top edge). Defaults match the
    // campus bar so a hand-written call still looks right.
    this.barHeight = 60,
    this.iconSize = 24,
    this.iconTop = 12,
    this.labelTop = 38,
    this.indW = 30,
    this.indH = 3,
    this.indTop = 0,
    this.indRadii = const [0, 0, 24, 24],
    // Bar SHAPE. All 0 = a flush, full-width, square bar (campus). Non-zero =
    // a FLOATING rounded pill inset from the edges (RailCab): sideL/sideR insets,
    // bottomMargin lift off the bottom, barRadius the corner rounding.
    this.sideL = 0,
    this.sideR = 0,
    this.bottomMargin = 0,
    this.barRadius = 0,
    // Bar drop shadow from Figma (null -> a soft default). RailCab's is subtle
    // and upward (dy -4, alpha .06).
    this.shadowColor,
    this.shadowDx = 0,
    this.shadowDy = 0,
    this.shadowBlur = 0,
    this.shadowSpread = 0,
    // Faint 1px pill outline (RailCab #E1E1E1). null -> no border.
    this.borderColor,
    this.borderWidth = 0,
  });
  final List<F2FNavItem> items;
  final int initialIndex;
  final Color barColor, activeColor, inactiveColor;
  final Color? indicatorColor; // null -> no indicator drawn
  final String fontFamily;
  final double fontSize;
  final double barHeight, iconSize, iconTop, labelTop, indW, indH, indTop;
  final List<double> indRadii; // [tl, tr, br, bl]
  final double sideL, sideR, bottomMargin, barRadius;
  final Color? shadowColor;
  final double shadowDx, shadowDy, shadowBlur, shadowSpread;
  final Color? borderColor;
  final double borderWidth;

  @override
  State<F2FBottomNavScaffold> createState() => _F2FBottomNavScaffoldState();
}

class _F2FBottomNavScaffoldState extends State<F2FBottomNavScaffold> {
  late int _i = widget.initialIndex.clamp(0, widget.items.length - 1);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // IndexedStack keeps every page alive (and its scroll/field state) while
      // showing only the selected one — the point of a real tab shell.
      // A FLOATING pill overlays the body's bottom exactly like Figma (the design
      // sheet fills to the frame bottom and the bar floats over its lower, empty
      // strip). extendBody lets the body reach behind the bar instead of being
      // pushed up by it — which was adding a screenful of dead scroll space.
      extendBody: _floating(),
      body: IndexedStack(
        index: _i,
        children: [for (final it in widget.items) it.page],
      ),
      bottomNavigationBar: _bar(),
    );
  }

  bool _floating() =>
      widget.sideL > 2 ||
      widget.sideR > 2 ||
      widget.bottomMargin > 2 ||
      widget.barRadius > 2;

  Widget _bar() {
    // Fixed to the design's bar height so every element lands at its exact Figma
    // y-offset instead of being packed by a Column.
    final row = SizedBox(
      height: widget.barHeight.w,
      child: Row(
        children: [for (var k = 0; k < widget.items.length; k++) _tab(k)],
      ),
    );
    final floating = _floating();
    // Flush, full-width, square bar (campus): a plain elevated Material strip.
    if (!floating) {
      return Material(
        color: widget.barColor,
        elevation: 8,
        child: SafeArea(top: false, child: row),
      );
    }
    // Floating rounded pill (RailCab): inset from the edges, lifted off the
    // bottom, rounded, with a soft shadow — reproduced from the captured shape.
    final r =
        widget.barRadius > widget.barHeight / 2 ? widget.barHeight / 2 : widget.barRadius;
    return SafeArea(
      top: false,
      child: Padding(
        padding: EdgeInsets.only(
          left: widget.sideL.w,
          right: widget.sideR.w,
          bottom: widget.bottomMargin.w,
          top: 6,
        ),
        child: Container(
          decoration: BoxDecoration(
            color: widget.barColor,
            borderRadius: BorderRadius.circular(r.w),
            border: widget.borderColor != null && widget.borderWidth > 0
                ? Border.all(color: widget.borderColor!, width: widget.borderWidth.w)
                : null,
            // Figma's own shadow when captured (subtle, often upward), else a
            // soft neutral default. Note the clip below is on the CHILD only, so
            // the shadow (painted outside the box) is not clipped away.
            boxShadow: [
              widget.shadowColor != null
                  ? BoxShadow(
                      color: widget.shadowColor!,
                      offset: Offset(widget.shadowDx.w, widget.shadowDy.w),
                      blurRadius: widget.shadowBlur.w,
                      spreadRadius: widget.shadowSpread.w)
                  : const BoxShadow(
                      color: Color(0x14000000),
                      blurRadius: 12,
                      offset: Offset(0, 2)),
            ],
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(r.w),
            child: row,
          ),
        ),
      ),
    );
  }

  Widget _tab(int k) {
    final it = widget.items[k];
    final on = k == _i;
    Widget at(double top, Widget child) =>
        Positioned(top: top.w, left: 0, right: 0, child: Center(child: child));
    // CENTER FAB (home's "Tree"): an elevated filled circle poking above the bar
    // with its label below. The glyph asset is usually the WHOLE FAB (circle +
    // icon baked into one svg), so it supplies its own fill; the coloured circle
    // is only a fallback when there is no asset.
    if (it.center) {
      final d = (it.fabSize > 0 ? it.fabSize : 48).toDouble();
      final fab = it.fabColor ?? widget.activeColor;
      final glyph = on ? (it.activeIcon ?? it.icon) : it.icon;
      return Expanded(
        child: InkWell(
          onTap: () => setState(() => _i = k),
          child: Stack(
            clipBehavior: Clip.none,
            children: [
              Positioned(
                top: -(d * 0.2).w,
                left: 0,
                right: 0,
                child: Center(
                  child: Container(
                    width: d.w,
                    height: d.w,
                    decoration: BoxDecoration(
                      color: glyph != null ? null : fab,
                      shape: BoxShape.circle,
                      boxShadow: [
                        BoxShadow(
                            color: fab.withValues(alpha: 0.45),
                            blurRadius: 10,
                            offset: const Offset(0, 4)),
                      ],
                    ),
                    child: glyph != null
                        ? ClipOval(
                            child: f2fAsset(glyph,
                                width: d.w, height: d.w, fit: BoxFit.cover))
                        : null,
                  ),
                ),
              ),
              at(
                widget.labelTop,
                Text(
                  it.label,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: gf(widget.fontFamily,
                      fontSize: widget.fontSize.sp,
                      fontWeight: on ? FontWeight.w600 : FontWeight.w400,
                      color: on ? widget.activeColor : widget.inactiveColor),
                ),
              ),
            ],
          ),
        ),
      );
    }
    return Expanded(
      child: InkWell(
        onTap: () => setState(() => _i = k),
        child: Stack(
          children: [
            if (on && widget.indicatorColor != null)
              at(
                widget.indTop,
                Container(
                  width: widget.indW.w,
                  height: widget.indH.w,
                  decoration: BoxDecoration(
                    color: widget.indicatorColor,
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(widget.indRadii[0].w),
                      topRight: Radius.circular(widget.indRadii[1].w),
                      bottomRight: Radius.circular(widget.indRadii[2].w),
                      bottomLeft: Radius.circular(widget.indRadii[3].w),
                    ),
                  ),
                ),
              ),
            if ((on ? (it.activeIcon ?? it.icon) : it.icon) != null)
              at(
                  widget.iconTop,
                  f2fAsset((on ? (it.activeIcon ?? it.icon) : it.icon)!,
                      width: widget.iconSize.w, height: widget.iconSize.w)),
            at(
              widget.labelTop,
              Text(
                it.label,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
                style: gf(widget.fontFamily,
                    fontSize: widget.fontSize.sp,
                    fontWeight: on ? FontWeight.w600 : FontWeight.w400,
                    color: on ? widget.activeColor : widget.inactiveColor),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// Merges N single-screen exports that share one TOP tab bar into ONE app shell,
/// the direct analogue of [F2FBottomNavScaffold] for a top strip. The strip is
/// LIFTED OUT of every body (the engine rendered the wide 10-tab strip as a
/// 991px Row of Spacers that cramps in a 390px frame); this widget reproduces it
/// as a real CUSTOM bar from captured Figma style and switches the body via an
/// [IndexedStack]. Two active-marker styles: an UNDERLINE (announcements —
/// [indicatorColor]) or a FILLED PILL (segmented Active/Past/Canceled —
/// [activePillColor]). The bar is pinned at [stripTop] (below the body's app
/// bar) so it stays put like a sticky tab bar while the body scrolls under it.
class F2FTopTabScaffold extends StatefulWidget {
  const F2FTopTabScaffold({
    super.key,
    required this.bodies,
    required this.tabLabels,
    required this.tabX,
    required this.tabW,
    required this.stripTop,
    required this.barHeight,
    this.initialIndex = 0,
    this.scrollable = false,
    this.barColor = Colors.white,
    this.activeColor = const Color(0xFF212121),
    this.inactiveColor = const Color(0xFF797979),
    this.fontFamily = 'Inter',
    this.fontSize = 14,
    this.labelTop = 16,
    // Underline marker (null -> the design uses a filled pill instead).
    this.indicatorColor,
    this.indW = 24,
    this.indH = 3,
    this.indTop = 48,
    this.indRadii = const [0, 0, 0, 0],
    // Bar bottom hairline.
    this.borderColor,
    this.borderWidth = 0,
    // Filled-pill marker (segmented). null activePillColor -> underline style.
    this.activePillColor,
    this.pillRadius = 0,
    this.pillTop = 0,
    this.pillH = 0,
    this.tabBorderColor,
    this.tabBorderWidth = 0,
    this.activeWeight = 700,
    this.inactiveWeight = 400,
    this.appBarTitle,
    this.appBarColor = Colors.white,
    this.appBarHeight = 0,
    this.appBarTitleColor = const Color(0xFF111827),
    this.appBarTitleSize = 18,
    this.appBarTitleWeight = 600,
    this.appBarFontFamily = 'Inter',
    this.appBarTitleTop = 52,
    this.appBarIcon,
    this.appBarIconLeft = 20,
    this.appBarIconTop = 52,
    this.appBarIconSize = 24,
  });
  // One body per tab slot: a real export, or null for an unexported tab (the
  // scaffold then renders app bar + centred label so the app bar stays fixed).
  final List<Widget?> bodies;
  final List<String> tabLabels;
  // Per-tab region in design px (frame-absolute). All scaled by .w to match the
  // bodies, which the engine lays out uniformly by width.
  final List<double> tabX, tabW;
  final double stripTop, barHeight;
  final int initialIndex;
  final bool scrollable;
  final Color barColor, activeColor, inactiveColor;
  final String fontFamily;
  final double fontSize, labelTop;
  final Color? indicatorColor;
  final double indW, indH, indTop;
  final List<double> indRadii;
  final Color? borderColor;
  final double borderWidth;
  final Color? activePillColor;
  final double pillRadius, pillTop, pillH;
  final Color? tabBorderColor;
  final double tabBorderWidth;
  final int activeWeight, inactiveWeight;
  final String? appBarTitle;
  final Color appBarColor, appBarTitleColor;
  final double appBarHeight, appBarTitleSize;
  final int appBarTitleWeight;
  final String appBarFontFamily;
  final double appBarTitleTop;
  final String? appBarIcon;
  final double appBarIconLeft, appBarIconTop, appBarIconSize;

  @override
  State<F2FTopTabScaffold> createState() => _F2FTopTabScaffoldState();
}

class _F2FTopTabScaffoldState extends State<F2FTopTabScaffold> {
  late int _i = widget.initialIndex.clamp(0, widget.bodies.length - 1);

  @override
  Widget build(BuildContext context) {
    // Material root: gives placeholder bodies a proper background + default text
    // style (else Flutter paints debug yellow-underlined text). The one Stack is
    // load-bearing — the bar sits BELOW the body's app bar, so it must overlay
    // the body at a fixed y, not sit above it in a Column.
    return Material(
      color: Colors.white,
      child: Stack(
        children: [
          // Keeps every page (and its scroll/field state) alive; shows only _i.
          IndexedStack(
            index: _i,
            children: [
              for (var k = 0; k < widget.bodies.length; k++)
                widget.bodies[k] ?? _placeholder(widget.tabLabels[k]),
            ],
          ),
          Positioned(
            top: widget.stripTop.w,
            left: 0,
            right: 0,
            child: _bar(),
          ),
        ],
      ),
    );
  }

  // An unexported tab still shows the fixed app bar (title band) + a centred
  // label, so switching to it never blanks the screen chrome.
  Widget _placeholder(String label) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        _appBar(),
        Expanded(
          child: Center(
            child: Text(label,
                style: gf(widget.appBarFontFamily,
                    fontSize: 18.sp, color: Colors.black54)),
          ),
        ),
      ],
    );
  }

  Widget _appBar() {
    final h = (widget.appBarHeight > 0 ? widget.appBarHeight : widget.stripTop);
    // Positions come straight from the captured bar so the reconstructed bar
    // lines up pixel-for-pixel with the real one — the title/icon don't jump
    // when switching to a placeholder tab.
    return SizedBox(
      height: h.w,
      child: Stack(
        children: [
          Positioned.fill(child: ColoredBox(color: widget.appBarColor)),
          if (widget.appBarIcon != null)
            Positioned(
              left: widget.appBarIconLeft.w,
              top: widget.appBarIconTop.w,
              child: f2fAsset(widget.appBarIcon!,
                  width: widget.appBarIconSize.w,
                  height: widget.appBarIconSize.w),
            )
          else
            Positioned(
              left: widget.appBarIconLeft.w,
              top: widget.appBarIconTop.w,
              child: Icon(Icons.arrow_back_ios_new,
                  size: widget.appBarIconSize.w, color: widget.appBarTitleColor),
            ),
          Positioned(
            top: widget.appBarTitleTop.w,
            left: 0,
            right: 0,
            child: Center(
              child: Text(
                widget.appBarTitle ?? '',
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
                style: gf(widget.appBarFontFamily,
                    fontSize: widget.appBarTitleSize.sp,
                    fontWeight: _fw(widget.appBarTitleWeight),
                    color: widget.appBarTitleColor),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _bar() {
    final n = widget.tabLabels.length;
    // Lay tabs out in a Row with the exact Figma leading pad + inter-tab GAPS
    // (derived from the captured x/w), NOT fixed-width slots — a fixed slot the
    // width of the Figma label clips the text to an ellipsis, because Flutter's
    // font renders a hair wider than Figma's. Content-sized tabs never clip.
    final row = <Widget>[];
    for (var k = 0; k < n; k++) {
      final lead = k == 0
          ? widget.tabX[0]
          : widget.tabX[k] - (widget.tabX[k - 1] + widget.tabW[k - 1]);
      if (lead > 0) row.add(SizedBox(width: lead.w));
      row.add(_tab(k));
    }
    final content = Row(mainAxisSize: MainAxisSize.min, children: row);
    return Container(
      height: widget.barHeight.w,
      decoration: BoxDecoration(
        color: widget.barColor,
        border: widget.borderColor != null && widget.borderWidth > 0
            ? Border(
                bottom: BorderSide(
                    color: widget.borderColor!, width: widget.borderWidth.w))
            : null,
      ),
      child: widget.scrollable
          ? SingleChildScrollView(
              scrollDirection: Axis.horizontal, child: content)
          : content,
    );
  }

  FontWeight _fw(int w) =>
      FontWeight.values[(w ~/ 100 - 1).clamp(0, FontWeight.values.length - 1)];

  Widget _tab(int k) {
    final on = k == _i;
    final label = Text(
      widget.tabLabels[k],
      maxLines: 1,
      softWrap: false,
      style: gf(widget.fontFamily,
          fontSize: widget.fontSize.sp,
          fontWeight: _fw(on ? widget.activeWeight : widget.inactiveWeight),
          color: on ? widget.activeColor : widget.inactiveColor),
    );
    Widget content;
    if (widget.activePillColor != null) {
      // FILLED-PILL (segmented): fixed-width pill (a button), active = solid
      // fill, inactive = faint outline, centred label.
      content = SizedBox(
        width: widget.tabW[k].w,
        height: widget.barHeight.w,
        child: Center(
          child: Container(
            width: widget.tabW[k].w,
            height: widget.pillH.w,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              color: on ? widget.activePillColor : null,
              borderRadius: BorderRadius.circular(widget.pillRadius.w),
              border: !on && widget.tabBorderColor != null
                  ? Border.all(
                      color: widget.tabBorderColor!,
                      width: widget.tabBorderWidth.w)
                  : null,
            ),
            child: label,
          ),
        ),
      );
    } else {
      // UNDERLINE (announcements): a content-sized Column — label at labelTop, a
      // Spacer, then the accent bar at indTop on the active tab. Content-sized
      // (no fixed slot) so the label never clips; the Column width hugs the label
      // (or the underline, whichever is wider). NOTE: a Stack of only Positioned
      // children collapses to zero width — hence the Column here.
      final bottomGap =
          (widget.barHeight - widget.indTop - widget.indH).clamp(0, widget.barHeight);
      content = SizedBox(
        height: widget.barHeight.w,
        child: Column(
          mainAxisSize: MainAxisSize.max,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            SizedBox(height: widget.labelTop.w),
            label,
            const Spacer(),
            if (on && widget.indicatorColor != null)
              Container(
                width: widget.indW.w,
                height: widget.indH.w,
                decoration: BoxDecoration(
                  color: widget.indicatorColor,
                  borderRadius: BorderRadius.only(
                    topLeft: Radius.circular(widget.indRadii[0].w),
                    topRight: Radius.circular(widget.indRadii[1].w),
                    bottomRight: Radius.circular(widget.indRadii[2].w),
                    bottomLeft: Radius.circular(widget.indRadii[3].w),
                  ),
                ),
              )
            else
              SizedBox(height: widget.indH.w),
            SizedBox(height: bottomGap.w),
          ],
        ),
      );
    }
    return InkWell(
      onTap: () => setState(() => _i = k.clamp(0, widget.bodies.length - 1)),
      child: content,
    );
  }
}

/// A horizontal strip that Figma exported PRE-SCROLLED (its content frame sits at
/// a strongly-negative local x so a middle item — an active tab — is the one on
/// screen). `SingleChildScrollView.initialScrollOffset` alone doesn't reproduce
/// it: the viewport's max extent is unknown when the scroll position is first
/// created, so the initial offset clamps to 0. This seeds the position AFTER the
/// first layout with a post-frame `jumpTo`, and owns/disposes the controller so
/// the host screen can stay a plain StatelessWidget.
class F2FPreScrolledStrip extends StatefulWidget {
  const F2FPreScrolledStrip(
      {super.key, required this.offset, required this.child});
  final double offset;
  final Widget child;
  @override
  State<F2FPreScrolledStrip> createState() => _F2FPreScrolledStripState();
}

class _F2FPreScrolledStripState extends State<F2FPreScrolledStrip> {
  final ScrollController _c = ScrollController();
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) => _seed(0));
  }

  // Seed the scroll position once the viewport has a real extent. Nested inside
  // the page's vertical scroll view, this horizontal strip's maxScrollExtent can
  // still be 0 on the first post-frame; retry a few frames until it resolves.
  void _seed(int tries) {
    if (!mounted) return;
    final ready = _c.hasClients && _c.position.hasContentDimensions;
    final max = ready ? _c.position.maxScrollExtent : 0.0;
    if ((!ready || max <= 0) && tries < 8) {
      WidgetsBinding.instance.addPostFrameCallback((_) => _seed(tries + 1));
      return;
    }
    if (_c.hasClients) _c.jumpTo(widget.offset.clamp(0.0, max));
  }

  @override
  void dispose() {
    _c.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        controller: _c,
        child: widget.child,
      );
}

/// A multi-segment donut chart. Figma exports each slice as a full concentric
/// ellipse (the arc angles are lost), so the engine recovers the slice weights
/// from the chart's legend counts and rebuilds the ring here.
class F2FDonutChart extends StatelessWidget {
  const F2FDonutChart({
    super.key,
    required this.size,
    required this.stroke,
    required this.values,
    required this.colors,
    this.startAngle = 0,
  });
  final double size;
  final double stroke;
  final List<double> values;
  final List<Color> colors;
  /// Where the first slice starts, radians clockwise from 12 o'clock.
  final double startAngle;
  @override
  Widget build(BuildContext context) => SizedBox(
        width: size,
        height: size,
        child: CustomPaint(
            painter: _F2FDonutPainter(values, colors, stroke, startAngle)),
      );
}

class _F2FDonutPainter extends CustomPainter {
  _F2FDonutPainter(this.values, this.colors, this.stroke, this.startAngle);
  final List<double> values;
  final List<Color> colors;
  final double stroke;
  final double startAngle;
  @override
  void paint(Canvas canvas, Size size) {
    final total = values.fold<double>(0, (a, b) => a + b);
    if (total <= 0) return;
    final rect = Rect.fromLTWH(stroke / 2, stroke / 2, size.width - stroke,
        size.height - stroke);
    var start = -math.pi / 2 + startAngle;
    const gap = 0.03; // small radian gap between slices
    for (var i = 0; i < values.length; i++) {
      final sweep = values[i] / total * (2 * math.pi);
      final paint = Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = stroke
        ..strokeCap = StrokeCap.butt
        ..color = colors[i % colors.length];
      final s = sweep > gap * 2 ? sweep - gap : sweep;
      canvas.drawArc(rect, start + gap / 2, s, false, paint);
      start += sweep;
    }
  }

  @override
  bool shouldRepaint(covariant _F2FDonutPainter old) =>
      old.values != values ||
      old.colors != colors ||
      old.stroke != stroke ||
      old.startAngle != startAngle;
}
