// GENERATED by Desynq — app entry point + a menu to open each screen.
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'theme.dart';
import 'category_grid_view_full.dart';
import 'product_detail_layout2.dart';

void main() => runApp(const DesynqApp());

class DesynqApp extends StatelessWidget {
  const DesynqApp({super.key});
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(375, 3333),
      minTextAdapt: true,
      // Screens are pixel-matched to the Figma frame, so the device font-size
      // setting must not reflow them, and glyphs sit centred in their line box
      // the way Figma measures text. Applied once for the whole app.
      builder: (context, _) => MediaQuery.withClampedTextScaling(
        minScaleFactor: 1.0,
        maxScaleFactor: 1.0,
        child: DefaultTextHeightBehavior(
          textHeightBehavior: const TextHeightBehavior(
            leadingDistribution: TextLeadingDistribution.even,
          ),
          child: MaterialApp(
            title: 'Desynq export',
            debugShowCheckedModeBanner: false,
            theme: FashionAppTheme.data(context),
            home: const _Menu(),
          ),
        ),
      ),
    );
  }
}

/// Re-initialises ScreenUtil at one screen's own design size before showing it.
Widget _sized(Size design, Widget child) => ScreenUtilInit(
      designSize: design,
      minTextAdapt: true,
      builder: (context, _) => child,
    );

class _Menu extends StatelessWidget {
  const _Menu();
  Widget _tile(BuildContext c, String label, WidgetBuilder b) => ListTile(
        title: Text(label),
        trailing: const Icon(Icons.chevron_right),
        onTap: () => Navigator.push(c, MaterialPageRoute(builder: b)),
      );
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Screens')),
      body: ListView(children: [
      _tile(context, 'Category Grid View Full', (_) => _sized(const Size(375, 3333), const CategoryGridViewFull())),
      _tile(context, 'Product Detail Layout2', (_) => _sized(const Size(375, 2971), const ProductDetailLayout2())),
      ]),
    );
  }
}
