import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import 'f2f_support.dart';

import 'package:flutter_svg/flutter_svg.dart';

import 'assets.dart';
import 'colors.dart';

// Auto-generated by figma2flutter. Verify against screenshot.
// designSize: 375.0 x 2971.0
class ProductDetailLayout2 extends StatefulWidget {
  const ProductDetailLayout2({super.key});

  @override
  State<ProductDetailLayout2> createState() => _ProductDetailLayout2State();
}

class _ProductDetailLayout2State extends State<ProductDetailLayout2> {
  final formKey = GlobalKey<FormState>();
  final addToBasket = TextEditingController();
  final addToBasketFocus = FocusNode();

  @override
  void dispose() {
    addToBasket.dispose();
    addToBasketFocus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: FashionAppColors.cFFFFFFFF,
      body: Form(
        key: formKey,
        child: SingleChildScrollView(
          padding: EdgeInsets.only(
            bottom: MediaQuery.viewPaddingOf(context).bottom,
          ),
          child: Container(
            width: 375.0.w,
            decoration: BoxDecoration(color: FashionAppColors.cFFFFFFFF),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                SvgPicture.asset(FashionAppAssets.header3, width: 375.0.w),
                SizedBox(height: 20.0.w),
                Image.asset(
                  FashionAppAssets.img,
                  width: 375.0.w,
                  height: 440.0.w,
                  fit: BoxFit.contain,
                ),
                SizedBox(height: 64.0.w),
                Padding(
                  padding: EdgeInsets.only(left: 16.0.w, bottom: 6.17.w),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              SizedBox(
                                width: 343.48.w,
                                child: Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment:
                                      MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Flexible(
                                      child: SizedBox(
                                        width: 86.0.w,
                                        child: Text(
                                          'MOHAN',
                                          style: gf(
                                            'Tenor Sans',
                                            fontSize: 16.0.sp,
                                            fontWeight: FontWeight.w400,
                                            color: FashionAppColors.cFF000000,
                                            letterSpacing: 4.0.w,
                                            height: 1.19,
                                          ),
                                          textAlign: TextAlign.center,
                                        ),
                                      ),
                                    ),
                                    SvgPicture.asset(
                                      FashionAppAssets.exportAsset,
                                      width: 16.0.w,
                                      height: 16.0.w,
                                      fit: BoxFit.contain,
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                          SizedBox(height: 8.0.w),
                          Text(
                            'Recycle Boucle Knit Cardigan Pink',
                            style: gf(
                              'Tenor Sans',
                              fontSize: 16.0.sp,
                              fontWeight: FontWeight.w400,
                              color: FashionAppColors.cFF555555,
                              letterSpacing: 0.0.w,
                              height: 1.19,
                            ),
                            textAlign: TextAlign.center,
                            maxLines: 1,
                            overflow: TextOverflow.ellipsis,
                          ),
                          SizedBox(height: 8.0.w),
                          Text(
                            '\$120',
                            style: gf(
                              'Tenor Sans',
                              fontSize: 18.0.sp,
                              fontWeight: FontWeight.w400,
                              color: FashionAppColors.cFFDD8560,
                              letterSpacing: 0.0.w,
                              height: 1.17,
                            ),
                            maxLines: 1,
                            overflow: TextOverflow.ellipsis,
                          ),
                        ],
                      ),
                      SizedBox(height: 21.32.w),
                      Row(
                        mainAxisSize: MainAxisSize.min,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          Flexible(
                            child: Text(
                              'Ring Size',
                              style: gf(
                                'Tenor Sans',
                                fontSize: 12.0.sp,
                                fontWeight: FontWeight.w400,
                                color: FashionAppColors.cFF555555,
                                letterSpacing: 0.0.w,
                                height: 1.17,
                              ),
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                          SizedBox(width: 11.22.w),
                          Row(
                            mainAxisSize: MainAxisSize.min,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                width: 24.0.w,
                                constraints: BoxConstraints(minHeight: 24.0.w),
                                decoration: BoxDecoration(
                                  color: FashionAppColors.cFF333333,
                                  borderRadius: BorderRadius.circular(12.0.w),
                                ),
                                child: ConstrainedBox(
                                  constraints: BoxConstraints(
                                    minHeight: 24.0.w,
                                  ),
                                  child: Center(
                                    child: FittedBox(
                                      fit: BoxFit.scaleDown,
                                      child: Text(
                                        '6',
                                        style: gf(
                                          'Tenor Sans',
                                          fontSize: 10.0.sp,
                                          fontWeight: FontWeight.w400,
                                          color: FashionAppColors.cFFF9F9F9,
                                          letterSpacing: 0.0.w,
                                          height: 1.2,
                                        ),
                                        textAlign: TextAlign.center,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              SizedBox(width: 6.0.w),
                              Container(
                                width: 24.0.w,
                                constraints: BoxConstraints(minHeight: 24.0.w),
                                decoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(12.0.w),
                                ),
                                foregroundDecoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(12.0.w),
                                  border: Border.all(
                                    color: FashionAppColors.cFFDEDEDE,
                                    width: 1.0.w,
                                    strokeAlign: BorderSide.strokeAlignInside,
                                  ),
                                ),
                                child: ConstrainedBox(
                                  constraints: BoxConstraints(
                                    minHeight: 24.0.w,
                                  ),
                                  child: Center(
                                    child: FittedBox(
                                      fit: BoxFit.scaleDown,
                                      child: Text(
                                        '8',
                                        style: gf(
                                          'Tenor Sans',
                                          fontSize: 10.0.sp,
                                          fontWeight: FontWeight.w400,
                                          color: FashionAppColors.cFF555555,
                                          letterSpacing: 0.0.w,
                                          height: 1.2,
                                        ),
                                        textAlign: TextAlign.center,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              SizedBox(width: 6.0.w),
                              Container(
                                width: 24.0.w,
                                constraints: BoxConstraints(minHeight: 24.0.w),
                                decoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(12.0.w),
                                ),
                                foregroundDecoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(12.0.w),
                                  border: Border.all(
                                    color: FashionAppColors.cFFDEDEDE,
                                    width: 1.0.w,
                                    strokeAlign: BorderSide.strokeAlignInside,
                                  ),
                                ),
                                child: ConstrainedBox(
                                  constraints: BoxConstraints(
                                    minHeight: 24.0.w,
                                  ),
                                  child: Center(
                                    child: FittedBox(
                                      fit: BoxFit.scaleDown,
                                      child: Text(
                                        '9',
                                        style: gf(
                                          'Tenor Sans',
                                          fontSize: 10.0.sp,
                                          fontWeight: FontWeight.w400,
                                          color: FashionAppColors.cFF555555,
                                          letterSpacing: 0.0.w,
                                          height: 1.2,
                                        ),
                                        textAlign: TextAlign.center,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              SizedBox(width: 6.0.w),
                              Container(
                                width: 24.0.w,
                                constraints: BoxConstraints(minHeight: 24.0.w),
                                decoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(12.0.w),
                                ),
                                foregroundDecoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(12.0.w),
                                  border: Border.all(
                                    color: FashionAppColors.cFFDEDEDE,
                                    width: 1.0.w,
                                    strokeAlign: BorderSide.strokeAlignInside,
                                  ),
                                ),
                                child: ConstrainedBox(
                                  constraints: BoxConstraints(
                                    minHeight: 24.0.w,
                                  ),
                                  child: Center(
                                    child: FittedBox(
                                      fit: BoxFit.scaleDown,
                                      child: Text(
                                        '10',
                                        style: gf(
                                          'Tenor Sans',
                                          fontSize: 10.0.sp,
                                          fontWeight: FontWeight.w400,
                                          color: FashionAppColors.cFF555555,
                                          letterSpacing: 0.0.w,
                                          height: 1.2,
                                        ),
                                        textAlign: TextAlign.center,
                                        maxLines: 1,
                                        overflow: TextOverflow.ellipsis,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              SizedBox(width: 6.0.w),
                              Container(
                                width: 24.0.w,
                                constraints: BoxConstraints(minHeight: 24.0.w),
                                decoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(12.0.w),
                                ),
                                foregroundDecoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(12.0.w),
                                  border: Border.all(
                                    color: FashionAppColors.cFFDEDEDE,
                                    width: 1.0.w,
                                    strokeAlign: BorderSide.strokeAlignInside,
                                  ),
                                ),
                                child: ConstrainedBox(
                                  constraints: BoxConstraints(
                                    minHeight: 24.0.w,
                                  ),
                                  child: Center(
                                    child: FittedBox(
                                      fit: BoxFit.scaleDown,
                                      child: Text(
                                        '11',
                                        style: gf(
                                          'Tenor Sans',
                                          fontSize: 10.0.sp,
                                          fontWeight: FontWeight.w400,
                                          color: FashionAppColors.cFF555555,
                                          letterSpacing: 0.0.w,
                                          height: 1.2,
                                        ),
                                        textAlign: TextAlign.center,
                                        maxLines: 1,
                                        overflow: TextOverflow.ellipsis,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                SizedBox(height: 26.52.w),
                Container(
                  width: 375.0.w,
                  constraints: BoxConstraints(minHeight: 56.0.w),
                  decoration: BoxDecoration(color: FashionAppColors.cFF000000),
                  child: GestureDetector(
                    behavior: HitTestBehavior.opaque,
                    onTap: addToBasketFocus.requestFocus,
                    child: InkWell(
                      onTap: () {}, // TODO: wire 'addToBasket'
                      child: Padding(
                        padding: EdgeInsets.only(
                          left: 16.0.w,
                          top: 17.3.w,
                          bottom: 14.09.w,
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            SizedBox(
                              width: 325.0.w,
                              child: Row(
                                mainAxisSize: MainAxisSize.max,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Flexible(
                                    child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      crossAxisAlignment:
                                          CrossAxisAlignment.center,
                                      children: [
                                        SvgPicture.asset(
                                          FashionAppAssets.plus,
                                          width: 20.0.w,
                                          height: 20.0.w,
                                          fit: BoxFit.contain,
                                        ),
                                        SizedBox(width: 7.81.w),
                                        Flexible(
                                          child: TextField(
                                            controller: addToBasket,
                                            focusNode: addToBasketFocus,
                                            style: gf(
                                              'Inter',
                                              fontSize: 14.0.sp,
                                              fontWeight: FontWeight.w400,
                                              color: FashionAppColors.cFFFCFCFC,
                                              letterSpacing: 0.14.w,
                                            ),
                                            cursorColor: FashionAppColors.cFFFCFCFC,
                                            decoration:
                                                InputDecoration.collapsed(
                                                  hintText: 'ADD TO BASKET',
                                                  hintStyle: gf(
                                                    'Inter',
                                                    fontSize: 14.0.sp,
                                                    fontWeight: FontWeight.w400,
                                                    color: FashionAppColors.cFFFCFCFC,
                                                    letterSpacing: 0.14.w,
                                                  ),
                                                ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  SizedBox(width: 153.19.w),
                                  SvgPicture.asset(
                                    FashionAppAssets.heart5,
                                    width: 24.0.w,
                                    height: 24.0.w,
                                    fit: BoxFit.contain,
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
                SizedBox(height: 29.48.w),
                Padding(
                  padding: EdgeInsets.only(left: 16.0.w),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Padding(
                        padding: EdgeInsets.only(left: 4.42.w),
                        child: Text(
                          'GALLERY',
                          style: gf(
                            'Tenor Sans',
                            fontSize: 14.0.sp,
                            fontWeight: FontWeight.w400,
                            color: FashionAppColors.cFF000000,
                            letterSpacing: 0.14.w,
                            height: 1.71,
                          ),
                        ),
                      ),
                      SizedBox(height: 10.07.w),
                      Image.asset(
                        FashionAppAssets.image16,
                        width: 343.0.w,
                        height: 167.72.w,
                        fit: BoxFit.cover,
                      ),
                      SizedBox(height: 16.8.w),
                      Image.asset(
                        FashionAppAssets.image17,
                        width: 343.0.w,
                        height: 343.0.w,
                        fit: BoxFit.cover,
                      ),
                      SizedBox(height: 15.31.w),
                      Image.asset(
                        FashionAppAssets.image18,
                        width: 343.0.w,
                        height: 257.25.w,
                        fit: BoxFit.cover,
                      ),
                    ],
                  ),
                ),
                SizedBox(height: 10.84.w),
                Padding(
                  padding: EdgeInsets.only(
                    left: 18.0.w,
                    top: 17.0.w,
                    bottom: 12.65.w,
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Padding(
                        padding: EdgeInsets.only(left: 2.42.w),
                        child: Text(
                          'CARE',
                          style: gf(
                            'Tenor Sans',
                            fontSize: 14.0.sp,
                            fontWeight: FontWeight.w400,
                            color: FashionAppColors.cFF000000,
                            letterSpacing: 0.14.w,
                            height: 1.71,
                          ),
                        ),
                      ),
                      SizedBox(height: 17.35.w),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          SizedBox(
                            width: 341.0.w,
                            child: Row(
                              mainAxisSize: MainAxisSize.max,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                Padding(
                                  padding: EdgeInsets.only(
                                    left: 1.2.w,
                                    top: 3.5.w,
                                    bottom: 3.09.w,
                                  ),
                                  child: Column(
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      Row(
                                        mainAxisSize: MainAxisSize.min,
                                        crossAxisAlignment:
                                            CrossAxisAlignment.center,
                                        children: [
                                          SizedBox(
                                            width: 12.0.w,
                                            height: 14.99.w,
                                            child: OverflowBox(
                                              minWidth: 0,
                                              minHeight: 0,
                                              maxWidth: 13.0.w,
                                              maxHeight: 16.0.w,
                                              alignment: Alignment.topLeft,
                                              child: Transform.translate(
                                                offset: Offset(-0.5.w, -0.5.w),
                                                child: SvgPicture.asset(
                                                  FashionAppAssets.vector24,
                                                  width: 13.0.w,
                                                  height: 16.0.w,
                                                ),
                                              ),
                                            ),
                                          ),
                                          SizedBox(width: 0.06.w),
                                          SizedBox(
                                            width: 8.92.w,
                                            height: 11.11.w,
                                            child: OverflowBox(
                                              minWidth: 0,
                                              minHeight: 0,
                                              maxWidth: 10.0.w,
                                              maxHeight: 13.0.w,
                                              alignment: Alignment.topLeft,
                                              child: Transform.translate(
                                                offset: Offset(-0.0.w, -0.5.w),
                                                child: SvgPicture.asset(
                                                  FashionAppAssets.vector22,
                                                  width: 10.0.w,
                                                  height: 13.0.w,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                      Row(
                                        mainAxisSize: MainAxisSize.min,
                                        crossAxisAlignment:
                                            CrossAxisAlignment.center,
                                        children: [
                                          Container(
                                            width: 2.5.w,
                                            height: 1.0.w,
                                            decoration: BoxDecoration(
                                              color: FashionAppColors.cFF000000,
                                            ),
                                          ),
                                          SvgPicture.asset(
                                            FashionAppAssets.ellipse66Stroke,
                                            width: 5.84.w,
                                            height: 5.84.w,
                                            fit: BoxFit.contain,
                                          ),
                                          Container(
                                            width: 6.73.w,
                                            height: 1.0.w,
                                            decoration: BoxDecoration(
                                              color: FashionAppColors.cFF000000,
                                            ),
                                          ),
                                          Container(
                                            width: 5.84.w,
                                            height: 5.84.w,
                                            decoration: BoxDecoration(
                                              borderRadius:
                                                  BorderRadius.circular(2.92.w),
                                            ),
                                            foregroundDecoration: BoxDecoration(
                                              borderRadius:
                                                  BorderRadius.circular(2.92.w),
                                              border: Border.all(
                                                color: FashionAppColors.cFF000000,
                                                width: 1.0.w,
                                                strokeAlign: BorderSide
                                                    .strokeAlignInside,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ),
                                SizedBox(width: 10.53.w),
                                Text(
                                  'Free Flat Rate Shipping',
                                  style: gf(
                                    'Tenor Sans',
                                    fontSize: 14.0.sp,
                                    fontWeight: FontWeight.w400,
                                    color: FashionAppColors.cFF000000,
                                    letterSpacing: 0.14.w,
                                    height: 1.71,
                                  ),
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                                const Spacer(),
                                SvgPicture.asset(
                                  FashionAppAssets.forward3,
                                  width: 24.0.w,
                                  height: 24.0.w,
                                  fit: BoxFit.contain,
                                ),
                              ],
                            ),
                          ),
                          SizedBox(height: 0.87.w),
                          Padding(
                            padding: EdgeInsets.only(left: 34.53.w),
                            child: SizedBox(
                              width: 286.0.w,
                              child: Text(
                                'Estimated to be delivered on \n09/11/2021 - 12/11/2021.',
                                style: gf(
                                  'Tenor Sans',
                                  fontSize: 14.0.sp,
                                  fontWeight: FontWeight.w400,
                                  color: FashionAppColors.cFF555555,
                                  letterSpacing: 0.0.w,
                                  height: 1.29,
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                      SizedBox(height: 2.0.w),
                      Padding(
                        padding: EdgeInsets.only(left: 34.94.w),
                        child: Opacity(
                          opacity: 0.2,
                          child: Container(
                            width: 306.06.w,
                            height: 1.0.w,
                            decoration: BoxDecoration(color: FashionAppColors.cFF555555),
                          ),
                        ),
                      ),
                      SizedBox(height: 5.92.w),
                      Padding(
                        padding: EdgeInsets.only(left: 1.0.w),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            SizedBox(
                              width: 340.0.w,
                              height: 20.0.w,
                              child: Stack(
                                clipBehavior: Clip.none,
                                children: [
                                  Positioned(
                                    left: 0.0.w,
                                    top: 10.0.w,
                                    child: FractionalTranslation(
                                      translation: const Offset(0, -0.5),
                                      child: SvgPicture.asset(
                                        FashionAppAssets.tag,
                                        width: 20.0.w,
                                        height: 20.0.w,
                                        fit: BoxFit.contain,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 32.53.w,
                                    top: 10.0.w,
                                    child: FractionalTranslation(
                                      translation: const Offset(0, -0.5),
                                      child: Text(
                                        'COD Policy',
                                        style: gf(
                                          'Tenor Sans',
                                          fontSize: 12.0.sp,
                                          fontWeight: FontWeight.w400,
                                          color: FashionAppColors.cFF000000,
                                          letterSpacing: 0.12.w,
                                          height: 2.0,
                                        ),
                                        maxLines: 1,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 315.0.w,
                                    top: 10.0.w,
                                    child: FractionalTranslation(
                                      translation: const Offset(0, -0.5),
                                      child: SvgPicture.asset(
                                        FashionAppAssets.forward2,
                                        width: 24.0.w,
                                        height: 24.0.w,
                                        fit: BoxFit.contain,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      SizedBox(height: 7.32.w),
                      Padding(
                        padding: EdgeInsets.only(left: 34.94.w),
                        child: Opacity(
                          opacity: 0.2,
                          child: Container(
                            width: 306.06.w,
                            height: 1.0.w,
                            decoration: BoxDecoration(color: FashionAppColors.cFF555555),
                          ),
                        ),
                      ),
                      SizedBox(height: 9.68.w),
                      Padding(
                        padding: EdgeInsets.only(left: 2.0.w),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            SizedBox(
                              width: 340.0.w,
                              height: 20.0.w,
                              child: Stack(
                                clipBehavior: Clip.none,
                                children: [
                                  Positioned(
                                    left: 0.0.w,
                                    top: 10.0.w,
                                    child: FractionalTranslation(
                                      translation: const Offset(0, -0.5),
                                      child: SvgPicture.asset(
                                        FashionAppAssets.refresh,
                                        width: 20.0.w,
                                        height: 20.0.w,
                                        fit: BoxFit.contain,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 32.53.w,
                                    top: 10.0.w,
                                    child: FractionalTranslation(
                                      translation: const Offset(0, -0.5),
                                      child: Text(
                                        'Return Policy',
                                        style: gf(
                                          'Tenor Sans',
                                          fontSize: 12.0.sp,
                                          fontWeight: FontWeight.w400,
                                          color: FashionAppColors.cFF000000,
                                          letterSpacing: 0.12.w,
                                          height: 2.0,
                                        ),
                                        maxLines: 1,
                                        overflow: TextOverflow.ellipsis,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 315.0.w,
                                    top: 10.0.w,
                                    child: FractionalTranslation(
                                      translation: const Offset(0, -0.5),
                                      child: SvgPicture.asset(
                                        FashionAppAssets.forward2,
                                        width: 24.0.w,
                                        height: 24.0.w,
                                        fit: BoxFit.contain,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                SizedBox(height: 24.0.w),
                Padding(
                  padding: EdgeInsets.only(bottom: 31.0.w),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Padding(
                        padding: EdgeInsets.only(left: 53.17.w),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Text(
                              'YOU MAY ALSO LIKE',
                              style: gf(
                                'Inter',
                                fontSize: 18.0.sp,
                                fontWeight: FontWeight.w400,
                                color: FashionAppColors.cFF000000,
                                letterSpacing: 4.0.w,
                                height: 2.22,
                              ),
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ),
                            SizedBox(height: 0.49.w),
                            Padding(
                              padding: EdgeInsets.only(left: 66.52.w),
                              child: SizedBox(
                                width: 124.96.w,
                                height: 9.25.w,
                                child: OverflowBox(
                                  minWidth: 0,
                                  minHeight: 0,
                                  maxWidth: 125.0.w,
                                  maxHeight: 10.0.w,
                                  alignment: Alignment.topLeft,
                                  child: Transform.translate(
                                    offset: Offset(-0.0.w, -0.0.w),
                                    child: SvgPicture.asset(
                                      FashionAppAssets.a5,
                                      width: 125.0.w,
                                      height: 10.0.w,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      SizedBox(height: 30.69.w),
                      Padding(
                        padding: EdgeInsets.only(left: 17.0.w),
                        child: Wrap(
                          spacing: 12.0.w,
                          runSpacing: 19.0.w,
                          children: [
                            _frame(_frameData[0], 0),
                            _frame(_frameData[1], 1),
                            _frame(_frameData[2], 2),
                            _frame(_frameData[3], 3),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                SizedBox(height: 16.0.w),
                Container(
                  width: 375.0.w,
                  constraints: BoxConstraints(minHeight: 340.0.w),
                  decoration: BoxDecoration(color: FashionAppColors.cFFFFFFFF),
                  child: Padding(
                    padding: EdgeInsets.only(top: 23.78.w),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Padding(
                          padding: EdgeInsets.only(left: 106.5.w),
                          child: SizedBox(
                            width: 162.0.w,
                            child: Row(
                              mainAxisSize: MainAxisSize.max,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                SvgPicture.asset(
                                  FashionAppAssets.twitter2,
                                  width: 24.0.w,
                                  height: 24.0.w,
                                  fit: BoxFit.contain,
                                ),
                                const Spacer(),
                                SvgPicture.asset(
                                  FashionAppAssets.instagram3,
                                  width: 24.0.w,
                                  height: 24.0.w,
                                  fit: BoxFit.contain,
                                ),
                                const Spacer(),
                                SvgPicture.asset(
                                  FashionAppAssets.youtube2,
                                  width: 24.0.w,
                                  height: 24.0.w,
                                  fit: BoxFit.contain,
                                ),
                              ],
                            ),
                          ),
                        ),
                        SizedBox(height: 24.0.w),
                        Padding(
                          padding: EdgeInsets.only(left: 125.02.w),
                          child: SizedBox(
                            width: 124.96.w,
                            height: 9.25.w,
                            child: OverflowBox(
                              minWidth: 0,
                              minHeight: 0,
                              maxWidth: 125.0.w,
                              maxHeight: 10.0.w,
                              alignment: Alignment.topLeft,
                              child: Transform.translate(
                                offset: Offset(-0.0.w, -0.0.w),
                                child: SvgPicture.asset(
                                  FashionAppAssets.a5,
                                  width: 125.0.w,
                                  height: 10.0.w,
                                ),
                              ),
                            ),
                          ),
                        ),
                        SizedBox(height: 18.73.w),
                        Padding(
                          padding: EdgeInsets.only(left: 95.0.w),
                          child: SizedBox(
                            width: 184.0.w,
                            height: 116.02.w,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0.0.w,
                                  top: 0.0.w,
                                  child: SizedBox(
                                    width: 202.4.w,
                                    child: Text(
                                      'support@openui.design\n+60 825 876\n08:00 - 22:00 - Everyday',
                                      style: gf(
                                        'Inter',
                                        fontSize: 16.0.sp,
                                        fontWeight: FontWeight.w400,
                                        color: FashionAppColors.cFF333333,
                                        letterSpacing: 0.0.w,
                                        height: 1.84,
                                      ),
                                      textAlign: TextAlign.center,
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 30.02.w,
                                  top: 106.76.w,
                                  child: SizedBox(
                                    width: 124.96.w,
                                    height: 9.25.w,
                                    child: OverflowBox(
                                      minWidth: 0,
                                      minHeight: 0,
                                      maxWidth: 125.0.w,
                                      maxHeight: 10.0.w,
                                      alignment: Alignment.topLeft,
                                      child: Transform.translate(
                                        offset: Offset(-0.0.w, -0.0.w),
                                        child: SvgPicture.asset(
                                          FashionAppAssets.a5,
                                          width: 125.0.w,
                                          height: 10.0.w,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        SizedBox(height: 32.0.w),
                        Padding(
                          padding: EdgeInsets.only(left: 58.0.w),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Flexible(
                                child: Text(
                                  'About',
                                  style: gf(
                                    'Inter',
                                    fontSize: 16.0.sp,
                                    fontWeight: FontWeight.w400,
                                    color: FashionAppColors.cFF000000,
                                    letterSpacing: 0.0.w,
                                    height: 1.5,
                                  ),
                                  textAlign: TextAlign.center,
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                              SizedBox(width: 52.0.w),
                              Flexible(
                                child: Text(
                                  'Contact',
                                  style: gf(
                                    'Inter',
                                    fontSize: 16.0.sp,
                                    fontWeight: FontWeight.w400,
                                    color: FashionAppColors.cFF000000,
                                    letterSpacing: 0.0.w,
                                    height: 1.5,
                                  ),
                                  textAlign: TextAlign.center,
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                              SizedBox(width: 52.0.w),
                              Flexible(
                                child: Text(
                                  'Blog',
                                  style: gf(
                                    'Inter',
                                    fontSize: 16.0.sp,
                                    fontWeight: FontWeight.w400,
                                    color: FashionAppColors.cFF000000,
                                    letterSpacing: 0.0.w,
                                    height: 1.5,
                                  ),
                                  textAlign: TextAlign.center,
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                            ],
                          ),
                        ),
                        SizedBox(height: 22.97.w),
                        InkWell(
                          onTap: () {}, // TODO: wire 'copyrightOpenuiAllRights'
                          child: Container(
                            width: 375.0.w,
                            height: 45.25.w,
                            decoration: BoxDecoration(
                              color: FashionAppColors.cFFC4C4C4,
                            ),
                            child: Padding(
                              padding: EdgeInsets.only(
                                top: 11.07.w,
                                bottom: 15.18.w,
                              ),
                              child: Center(
                                child: Text(
                                  'Copyright© OpenUI All Rights Reserved.',
                                  style: gf(
                                    'Inter',
                                    fontSize: 12.0.sp,
                                    fontWeight: FontWeight.w400,
                                    color: FashionAppColors.cFF555555,
                                    letterSpacing: 0.0.w,
                                    height: 1.58,
                                  ),
                                  textAlign: TextAlign.center,
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  /// Extracted from Frame 21 — 4 instances in the design.
  Widget _frame(Map<String, String> d, int index) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: [
        SizedBox(
          width: 165.0.w,
          height: 220.0.w,
          child: Stack(
            children: [
              Positioned(
                left: 0.0.w,
                top: 0.0.w,
                child: Image.asset(
                  d['image'] ?? '',
                  width: 165.0.w,
                  height: 220.0.w,
                  fit: BoxFit.cover,
                ),
              ),
              Positioned(
                left: 140.0.w,
                top: 198.0.w,
                child: SvgPicture.asset(
                  FashionAppAssets.heart4,
                  width: 16.0.w,
                  height: 16.0.w,
                  fit: BoxFit.contain,
                ),
              ),
            ],
          ),
        ),
        SizedBox(height: 8.0.w),
        Padding(
          padding: EdgeInsets.only(left: 4.0.w),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(
                    '21WN ',
                    style: gf(
                      'Tenor Sans',
                      fontSize: 12.0.sp,
                      fontWeight: FontWeight.w400,
                      color: FashionAppColors.cFF000000,
                      letterSpacing: 0.0.w,
                      height: 1.5,
                    ),
                  ),
                  Text(
                    'reversible angora cardigan',
                    style: gf(
                      'Tenor Sans',
                      fontSize: 12.0.sp,
                      fontWeight: FontWeight.w400,
                      color: FashionAppColors.cFF555555,
                      letterSpacing: 0.0.w,
                      height: 1.5,
                    ),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                ],
              ),
              SizedBox(height: 4.0.w),
              Text(
                '\$120',
                style: gf(
                  'Tenor Sans',
                  fontSize: 15.0.sp,
                  fontWeight: FontWeight.w400,
                  color: FashionAppColors.cFFDD8560,
                  letterSpacing: 0.0.w,
                  height: 1.6,
                ),
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
            ],
          ),
        ),
      ],
    );
  }
}

const _frameData = <Map<String, String>>[
  {'image': 'assets/images/79ef714ae60e.png'},
  {'image': 'assets/images/a9628debcc2c.png'},
  {'image': 'assets/images/0a071ac09f7e.png'},
  {'image': 'assets/images/d2e089c8140c.png'},
];