// GENERATED by figma2flutter — shared theme. Do not edit by hand.
// One theme per project instead of one copy per screen.
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:google_fonts/google_fonts.dart';
import 'colors.dart';

class FashionAppTheme {
  FashionAppTheme._();

  static ThemeData data(BuildContext context) {
    return ThemeData(
      useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(
        seedColor: FashionAppColors.cFFC4C4C4,
        primary: FashionAppColors.cFFC4C4C4,
        onPrimary: FashionAppColors.cFF555555,
      ),
      scaffoldBackgroundColor: FashionAppColors.cFFFFFFFF,
      textTheme: GoogleFonts.interTextTheme(),
      appBarTheme: AppBarTheme(
        backgroundColor: FashionAppColors.cFFFFFFFF,
        foregroundColor: FashionAppColors.cFF000000,
        elevation: 0,
        centerTitle: false,
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: false,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12.0.w),
          borderSide: BorderSide.none,
        ),
      ),
    );
  }
}